on:
  push:
    tags:
      - 'alpha/v*-alpha.*'
      - 'beta/v*-beta.*'
      - 'rc/v*-rc.*'

jobs:
  extract:
    runs-on: ubuntu-latest
    outputs:
      channel: ${{ steps.setvars.outputs.channel }}
      snapshot_serial: ${{ steps.setvars.outputs.snapshot_serial }}
    steps:
      - name: Extract the SemVer Version Code
        id: setvars
        run: |
          tag="${GITHUB_REF#refs/tags/}"

          # Get the prefix (channel): alpha, beta, rc
          channel="${tag%%/*}"
          # Get the suffix after last dash, e.g. "alpha.5" -> "5"
          snapshot_serial="${tag##*-}"

          echo "tag=$tag"
          echo "channel=$channel"
          echo "snapshot_serial=$snapshot_serial"

          echo "channel=$channel" >> $GITHUB_OUTPUT
          echo "snapshot_serial=$snapshot_serial" >> $GITHUB_OUTPUT

  build:
    needs: extract
    uses: ./.github/workflows/build.yml
    with:
      channel: ${{ needs.extract.outputs.channel }}
      snapshot_serial: ${{ needs.extract.outputs.snapshot_serial }}
      branch: ${{ github.ref }}
      publish: true
    secrets:
      KUAYUE_MAVEN_USERNAME: ${{ secrets.KUAYUE_MAVEN_USERNAME }}
      KUAYUE_MAVEN_PASSWORD: ${{ secrets.KUAYUE_MAVEN_PASSWORD }}