on:
  push:
    branches:
      - 'alpha/*'
      - 'beta/*'
      - 'rc/*'
    tags:
      - 'alpha/v*-alpha.*'
      - 'beta/v*-beta.*'
      - 'rc/v*-rc.*'
      - 'alpha/v*-*-alpha.*'
      - 'beta/v*-*-beta.*'
      - 'rc/v*-*-rc.*'
      - 'alpha/v*-*-*-alpha.*'
      - 'beta/v*-*-*-beta.*'
      - 'rc/v*-*-*-rc.*'

jobs:
  extract:
    runs-on: ubuntu-latest
    outputs:
      channel: ${{ steps.setvars.outputs.channel }}
      snapshot_serial: ${{ steps.setvars.outputs.snapshot_serial }}
    steps:
      - name: Extract infromation from SemVer
        id: setvars
        run: |
          tag="${GITHUB_REF#refs/tags/}"

          echo "$tag" | awk -F/ '
          {
            channel = $1
            tag_body = $2
            
            if (match(tag_body, /-(alpha|beta|rc)\.[0-9]+$/)) {
            matched = substr(tag_body, RSTART, RLENGTH)
            if (match(matched, /[0-9]+/)) {
            snapshot_serial = substr(matched, RSTART, RLENGTH)
          } else {
            snapshot_serial = "0"
          }
          } else {
            snapshot_serial = "0"
          }
        
            print "channel=" channel
            print "snapshot_serial=" snapshot_serial
          }
          '
  build:
    needs: extract
    uses: ./.github/workflows/build.yml
    with:
      channel: ${{ needs.extract.outputs.channel }}
      snapshot_serial: ${{ needs.extract.outputs.snapshot_serial }}
      branch: ${{ github.ref }}
      publish: true
    secrets:
      KUAYUE_MAVEN_USERNAME: ${{ secrets.KUAYUE_MAVEN_USERNAME }}
      KUAYUE_MAVEN_PASSWORD: ${{ secrets.KUAYUE_MAVEN_PASSWORD }}